### ISSUE TITLE
Plugin doesn't work

### ISSUE THREAD

**Issue by RogerSik** [pygillier/munin-7dtd#5]
Hi,

when i try to use your both plugin on a Ubuntu 15.04 server I get following error in the munin-node.log

2015/10/15-16:50:02 CONNECT TCP Peer: "[::ffff:192.168.1.16]:37707" Local: "[::ffff:192.168.1.14]:4949"
2015/10/15-16:50:02 [24136] Error output from 7d2d_mem:
2015/10/15-16:50:02 [24136]     Traceback (most recent call last):
2015/10/15-16:50:02 [24136]       File "/etc/munin/plugins/7d2d_mem", line 79, in <module>
2015/10/15-16:50:02 [24136]         main()
2015/10/15-16:50:02 [24136]       File "/etc/munin/plugins/7d2d_mem", line 76, in main
2015/10/15-16:50:02 [24136]         report()
2015/10/15-16:50:02 [24136]       File "/etc/munin/plugins/7d2d_mem", line 56, in report
2015/10/15-16:50:02 [24136]         print "heap.value %0.2f" % float(heap_mem)
2015/10/15-16:50:02 [24136]     ValueError: invalid literal for float(): 423,5
2015/10/15-16:50:02 [24136] Service '7d2d_mem' exited with status 1/0.
2015/10/15-16:50:06 [24136] Error output from 7d2d_users:
2015/10/15-16:50:06 [24136]     Traceback (most recent call last):
2015/10/15-16:50:06 [24136]       File "/etc/munin/plugins/7d2d_users", line 85, in <module>
2015/10/15-16:50:06 [24136]         main()
2015/10/15-16:50:06 [24136]       File "/etc/munin/plugins/7d2d_users", line 82, in main
2015/10/15-16:50:06 [24136]         report()
2015/10/15-16:50:06 [24136]       File "/etc/munin/plugins/7d2d_users", line 59, in report
2015/10/15-16:50:06 [24136]         known_users = m.group(1)
2015/10/15-16:50:06 [24136]     AttributeError: 'NoneType' object has no attribute 'group'
2015/10/15-16:50:06 [24136] Service '7d2d_users' exited with status 1/0.

telnet ist enabled and reachable from localhost 

The munin-node with the plugins is installed on the game server. Munin itself is installed on another server and fetch from the game-server the informations.

**Comment by pygillier** [comment]
Hi, which version of the 7DTD server are you running ? 

it seems to be related to a format change in `mem` command output on telnet console. 

Do you always have this error or not ?

**Comment by RogerSik** [comment]
Hi,

the version is Alpha 12.5 (612). 

I have always this error.
